### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by buinauskas** [mwilliammyers/elastiql#10]
Hi, this is not an issue but rather a question.

We've started building an API in Rust that uses Elasticsearch as a data store. Naturally, I've started to build strongly typed queries and soon after I've found this project which does exactly that.

I wouldn't want to duplicate efforts and would prefer to switch to this project and contribute myself (as much as I could), however I'm not entirely sure about its status, maintenance, future plans, etc?

Thank you,
Evaldas

**Comment by mwilliammyers** [comment]
Hi! Sorry I missed this. 

We are currently using it in production and it fits our needs well. The API is still under development so we don't have any stability guarantees or anything like that right now. It is fairly feature complete as far as a search query builder is concerned, but it is missing some APIs and options.

We don't have any explicit maintenance guarantees or plans for it other than our company is going to be using it and so we will continue to support its development at least as far as our business needs are concerned. I would love to see it either merged into the official Elasticsearch client in some form (see [elastic/elasticsearch-rs#75](https://github.com/elastic/elasticsearch-rs/issues/75)) or have this project grow and complement the official crate as a standalone crate.
